create script.js file
neoThobela/myportfolio pull request #1
Opened 2024-10-25 13:21 UTC by neoThobela

<p>this is my js file for my chatbot</p>

2024-11-04 09:16 UTC, kgaugelomokgalaka commented
the code is good , easy to be read by the other person
overall its a good code

2024-11-04 09:41 UTC, ManeoMalatsi commented
I like your colours and chatbot, please show how to insert the icon

2024-11-04 09:41 UTC, NthabisengLekolwana commented
i love it, its friendly.

2024-11-05 07:41 UTC, NthabisengLekolwana requested changes
You did not update your read me file after adding the chatbot to your website

2024-11-05 08:03 UTC, XolaniMba commented on script.js
> +};
@neoThobela  The chatbot responses are really good!

2024-11-05 08:03 UTC, XolaniMba approved these changes

2024-11-05 08:15 UTC, kgaugelomokgalaka reviewed
your code look good 
please just reduce the amount of comments in your css file

2024-11-05 08:25 UTC, ManeoMalatsi approved these changes

2024-11-05 08:27 UTC, neoThobela commented
@NthabisengLekolwana  thank you ive updated it.

2024-11-05 10:11 UTC, NthabisengLekolwana approved these changes

2024-11-05 13:38 UTC, neoThobela commented
> your code look good please just reduce the amount of comments in your css file

@kgaugelomokgalaka done thank you

2024-11-05 13:38 UTC, merged